### ISSUE TITLE
Not able to clone and code after forking for Servicenow

### ISSUE THREAD

**Issue by Nnennasy** [ServiceNow/devtraining-needit-paris#97]
hi i am unable to clone even though i have forked but it did not download

![image](https://user-images.githubusercontent.com/77815667/105530263-c71eab80-5ca4-11eb-932b-61b216435ac2.png)

**Comment by hpham001** [comment]
I have the same problem. 
The application is cloned manually, and ported to my github, SN imported from source control OK, but it just a blank application, no table, nothing, and cannot go on with the development course.

**Comment by bsweets** [comment]
Please send feedback from the page in the learning content with your questions. That will help us know where you are so we can best help you. This opens a task for us to track your question.

Immediately after loading the application, you will not see anything. We use branches and tags to get your instance configured with what you need for the learning module you are in. The directions include the steps to create the branch. 

For more information about how we are using GitHub with our learning content, you can read the [GitHub Guide](https://developer.servicenow.com/dev.do#!/guides/paris/developer-program/github-guide/github-and-the-developer-site-training-guide-introduction) on the Developer Site.

**Comment by Nnennasy** [comment]
Hi,
I still was unable to get it loaded...
Nnenna 


    On Monday, February 1, 2021, 06:11:09 a.m. MST, Ben Sweetser <notifications@github.com> wrote:  
 
 


Closed #97.

**Comment by bsweets** [comment]
Please send feedback from the page in the learning content you are working on so we can better assist you. In the screenshot above, you are copying the link from the main repository, not your fork. Be sure you see Nnennasy in the URL you copy to use in ServiceNow.
